config/routes.rb
Rails.application.routes.draw do

  resources:articulos do
    resources:comentarios
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Esta ruta dirige la pagina principal al index que se creo

  root 'bienvenido#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/articulo.rb
class Articulo < ApplicationRecord
  has_many :comentarios, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :articulo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  http_basic_authenticate_with name: "nasugo", password: "JEPA", except: [:index, :show]
  def index
    @articulos = Articulo.all
  end
  def show
    # id le dice a rails que esta ruta espera un parametro :id, que en nuestro caso sera el id del articulo
    @articulo = Articulo.find(params[:id])
  end
#
  def new
    @articulo = Articulo.new
  end
#
  def edit
    @articulo = Articulo.find(params[:id])
  end
#
  def create
    #metodo del controlador los datos del form(articulos) como texto plano
    # params[]es un objeto que representa los parametros que vienen del formulario
    #render plain: params[:articulo].inspect

    @articulo = Articulo.new(articulo_params)
    #retorna un boolean indicando si fue o no creada
      if @articulo.save
        redirect_to @articulo
      else
        render 'new'
      end

  end
  #
  def update
    @articulo = Articulo.find(params[:id])
    #retorna un boolean indicando si fue o no creada
      if @articulo.update(articulo_params)
        redirect_to @articulo
      else
        render 'edit'
      end
  end
  #
  def destroy
    @articulo = Articulo.find(params[:id])
    @articulo.destroy
    redirect_to @articulo

  end

  private
    def articulo_params
      params.require(:articulo).permit(:title, :text)
    end
end

app/controllers/bienvenido_controller.rb
class BienvenidoController < ApplicationController
  def index
  end
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  http_basic_authenticate_with name: "nasugo", password: "JEPA", only: :destroy
  def create
    @articulo = Articulo.find(params[:articulo_id])
    # para crear el comentario dentro del articulo
    @comentario = @articulo.comentarios.create(comentario_params)
    #redirigimos a la vista show del articulo
    redirect_to articulo_path(@articulo)
  end
  def destroy
    @articulo = Articulo.find(params[:articulo_id])
    @comentario = @articulo.comentarios.find(params[:id])
    @comentario.destroy
    redirect_to articulo_path(@articulo)

  end
private
  def comentario_params
      params.require(:comentario).permit(:nombre, :cuerpo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/articulos/_form.html.erb
<%= form_with model: @articulo,  local: true do |form|%>

<% if @articulo.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@articulo.errors.count, "error")%> ERROR
      Este articulo se guarda
    </h2>
    <ul>
      <% @articulo.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= form.label :Titulo %> <br>
    <%= form.text_field :title%>
  </p>
  <p>
    <%= form.label :Texto %> <br>
    <%= form.text_area :text%>
  </p>
  <p>
    <%= form.submit %>
  </p>
  <% end %>

  <%= link_to 'Regresar', articulos_path%>

app/views/articulos/edit.html.erb
<h1>Edicion de articulos</h1>


<%= render 'form' %>

<%= link_to 'Regresar', articulos_path%>

app/views/articulos/index.html.erb
<h1>Lista de articulos</h1>

<table>
  <tr>
    <th>Titulo</th>
    <th>Texto</th>
    <th></th>
  </tr>
  <% @articulos.each do |articulo|%>
    <tr>
      <td><%= articulo.title%></td>
      <td><%= articulo.text%></td>
      <td><%= link_to 'Show', articulo_path(articulo)%></td>
      <td><%= link_to 'Editar', edit_articulo_path(articulo)%></td>
      <td><%= link_to 'Eliminar',articulo_path(articulo),
              method: :delete,
              data: {confirm: 'Confirma eliminacion'}
              %></td>

    </tr>
    <% end %>
</table>
<%= link_to 'Crear', new_articulo_path %>

app/views/articulos/new.html.erb
<h1>Nuevo post</h1>



<%= render 'form' %>


<%= link_to 'Regresar', articulos_path%>

app/views/articulos/show.html.erb
<p>
<strong> Title:</strong>
<%= @articulo.title %>
</p>
<p>
<strong> Texto: </strong>
<%= @articulo.text %>
</p>
<p><%= link_to 'Editar', edit_articulo_path(@articulo)%> </p>
<p><%= link_to 'Regresar', articulos_path%> </p>

<h2>Comentarios</h2>

<% # reeemplza lo que hay en la vista parcial _comentarios%>
<%= render @articulo.comentarios%>


<h2>Agregar comentario</h2>
<%= render 'comentarios/form' %>

app/views/bienvenido/index.html.erb
<h1>Bienvenido#index</h1>

<p>Hola RoR</p>
<%= link_to 'Mi blog', articulos_path%>

app/views/comentarios/_comentario.html.erb
<% @articulo.comentarios.each do |comentario|%>
<h2>Comentarios</h2>

<p>
  <strong>Comenta: </strong>
  <%= comentario.nombre%>
</p>
<p>
  <strong>Comentario: </strong>
  <%= comentario.cuerpo%>
</p>

<p>
  <%= link_to 'Eliminar Comentario', [comentario.articulo, comentario],
               method: :delete,
               data: { confirm: '¿Estas seguro de eliminar el comentario?' } %>
</p>

  <% end %>

app/views/comentarios/_form.html.erb
<%= form_with model: [ @articulo, @articulo.comentarios.build ],  local: true do |form|%>


  <p>
    <%= form.label :Nomnre %> <br>
    <%= form.text_field :nombre%>
  </p>
  <p>
    <%= form.label :Cuerpo %> <br>
    <%= form.text_area :cuerpo%>
  </p>
  <p>
    <%= form.submit %>
  </p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>